devices:
  - name: sxt2ghz
    host: 192.168.88.2
    username: admin
    password: admin
    type: routerboard
  - name: sxt5ghz
    host: 192.168.88.5
    username: admin
    password: admin
    type: routerboard
  - name: nanobridge
    host: 192.168.88.25
    username: ubnt
    password: ubnt
    type: ubiquiti